# Generated by Django 5.0.6 on 2024-06-29 09:25

import measurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=measurement.models.upload_path_handler),
        ),
    ]
