# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP34",
  "description": "Датчик в ванной"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик в кабинет"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json
s
{
  "sensor": 2,
  "temperature": 25.7
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
