# примеры API-запросов

# admin = 63b2706b27fc17e0d3a59f6f0688d88cb3b1d451
# user = 1520154378ebd1d6af013b8bcf2da7df3d41d501

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 1520154378ebd1d6af013b8bcf2da7df3d41d501

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 63b2706b27fc17e0d3a59f6f0688d88cb3b1d451

{
  "title": "Шкаф IKEA 12",
  "description": "Срочно",
  "status": "DRAFT"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/19/
Content-Type: application/json
Authorization: Token 63b2706b27fc17e0d3a59f6f0688d88cb3b1d451

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
